timmo001/system-bridge-connector-py

systembridge/client/__init__.py

Add missing good response statuses

---

setup.py

Bump version to v1.0.0

---

systembridge/client/__init__.py

Raise Auth exception with 403 responses

---

systembridge/client/__init__.py

Remove kwargs from exceptions

---

systembridge/__init__.py
systembridge/objects/settings/__init__.py

Settings endpoint

---

test.py

Add test class

---

systembridge/__init__.py
systembridge/objects/media/__init__.py
systembridge/objects/media/delete.py
systembridge/objects/media/post.py
systembridge/objects/media/put.py
systembridge/objects/video/__init__.py
test.py

Media endpoint

---

requirements.txt
setup.py
systembridge/__init__.py
systembridge/client/__init__.py
systembridge/client_websocket/__init__.py
systembridge/objects/events/__init__.py
test.py

WebSocket and Events

---

systembridge/__init__.py

Fix event setting

---

systembridge/__init__.py
test.py

Remove get cover, add media cover url

---

setup.py
systembridge/objects/media/__init__.py

Add has cover media property

---

systembridge/objects/os.py

Add idle time to os

---

systembridge/__init__.py
systembridge/objects/information.py

Add information endpoint

---

setup.py
systembridge/client_websocket/__init__.py
systembridge/exceptions.py

WS connection closed exception

---

systembridge/__init__.py
systembridge/client_websocket/__init__.py

Register listener rename

---

systembridge/__init__.py

Update data from WebSocket

---

setup.py
systembridge/__init__.py
systembridge/client_websocket/__init__.py

Websocket connection handling

---

systembridge/client_websocket/__init__.py

Remove reference to ClientConnection

---

systembridge/__init__.py
systembridge/objects/display/__init__.py

Fix display endpoint

---

setup.py
systembridge/objects/display/__init__.py

Add display refresh rate

---

systembridge/__init__.py

Add configuration url property

---

systembridge/__init__.py

WebSocket Handle non findAll methods

---

setup.py
systembridge/__init__.py

Fix-existing-data
